export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";

export const SEND_CONTACT_FORM_SUCCESS = "SEND_CONTACT_FORM_SUCCESS";
